CREATE TABLE ST AS SELECT * FROM ALL_USERS;

CREATE INDEX STI ON ST(USERNAME);

SELECT COUNT(*) FROM ST;

SELECT NUM_ROWS, LAST_ANALYZED FROM USER_TABLES WHERE TABLE_NAME = 'ST';

SELECT DISTINCT_KEYS, LAST_ANALYZED FROM USER_INDEXES WHERE INDEX_NAME = 'STI';

EXEC DBMS_STATS.GATHER_TABLE_STATS('SYSTEM', 'ST');

INSERT INTO ST SELECT * FROM ALL_USERS;

SELECT NUM_ROWS, LAST_ANALYZED FROM USER_TABLES WHERE TABLE_NAME = 'ST';

SELECT DISTINCT_KEYS, LAST_ANALYZED FROM USER_INDEXES WHERE INDEX_NAME = 'STI';

EXEC DBMS_STATS.GATHER_SCHEMA_STATS('SYSTEM');

DROP TABLE ST;