--- teste no sqlplus

alter session set "_ORACLE_SCRIPT"=true;

CREATE USER userexample IDENTIFIED BY userexample;

GRANT DBA TO userexample;

CONNECT userexample/userexample;

CREATE TABLE TB AS SELECT * FROM ALL_OBJECTS;

SELECT MAX(OBJECT_ID) FROM TB;

VARIABLE vtask VARCHAR2(100);

EXECUTE :vtask:=DBMS_SQLTUNE.CREATE_TUNING_TASK(sql_text=>'SELECT MAX(OBJECT_ID) FROM TB');

EXECUTE DBMS_SQLTUNE.EXECUTE_TUNING_TASK(:vtask);

SELECT DBMS_SQLTUNE.REPORT_TUNNING_TASK(:vtask) FROM DUAL;

SET LONG 10000;

SET LONGCHUNKSIZE 10000;

CONNECT system/root;

DROP USER userexample CASCADE;